Study 3 -  The influence of learning through motor engagement on shape representation in pathways and motor pathways

* intro

        In this experiment, we will use fMRI to examine and compare the neural representation of visual shapes during viewing of static shape templates which were learned either through motor engagement (shape production) or through observation only.

        Our hypothesis is that the neural representations engendered by motor engagement will be distinct from those acquired by visual learning  - reflecting reliance of the representation on the circuits involved in the method of learning.
        Specifically, we will ask two questions:
        1. Can the training regimen/learning method be inferred from brain activity during shape observation? (Or - is the neural representation modulated by training regimen/motor engagement?)
        2. In subjects who underwent motor training - is there a correlation between our ability to decode the specific shape being observed and behavioral and kinematic measures of the training procedure?  [Should we add reference here to   (1)  a subject's score in the visual assessment, or (2) kinematic measures of their drawing during training, such as smoothness and accuracy.?]

* Participants
        Same as study 2

* Procedure
    To address our two questions, participants will be engaged in three experimental sessions - two behavioral training and assessment sessions followed by an fMRI scanning session.
    During the behavioral session, participants will be divided into two groups: a visuomotor training group, which will actively trace over the shape templates, and a visual training group which will be presented with traces collected from the visoumotor group superimposed over the templates.
    The behavioral session will begin with a familiarization phase, during which participants will become acquainted with the task and setup, followed by an initial visual assessment.
    After the initial assessment participants will proceed to train in accordance with the group which they belong to. At the end of the training phase participants will preform a second visual assessment.
    The visuomotor group will be presented with shape templates and instructed to trace them  in the manner that they judge will be most conducive to their learning of the shapes. Participants will have a 10s time-window to complete the drawing, and slow trials will be interrupted and discarded. Tracing will be performed with their right hand only, using a stylus on a large touch sensitive screen, situated such that the screen and the drawing hand are blocked [obscured] from view. The  shape template and tracing feedback will be presented on a separate screen, positioned just above the screen which participants use for drawing.This setup is to ensure the visual aspect of the task remain constant between the visuomotor and visual-only groups.

*** TODO integrate with shlomit's BSF_2021_v1:
    Training task: Each participant will be randomly assigned to one of six training task groups which include two visuo-motor training regimen groups (right / left hand tracing), and four visual training regimen groups (dynamic / static visual input, from right/left hand traces).
    Visuo-motor training will include tracing of shapes and receiving visual feedback of the trace as it is formed. Participants assigned to one of the visuo-motor training regimens will be asked to use an electronic stylus to trace a template of a different shape in each trial. Shapes from the training set will be randomly ordered across training. Shapes will be traced continuously for one full cycle, in a comfortable natural pace. Participants will see the reference template throughout the trial, and their trace will form in real-time overlaid on the template, as if drawing with a pen on paper. Any starting position and direction of tracing can be freely chosen by the participant. Prior to the training session on the first day, each shape will also be traced one time in a pre-training run, so participants are comfortable with the set-up and familiar with the shapes before training begins. Tracing will be performed either using the non-dominant left hand or the dominant right hand, according to the assigned training group (Fig 3B upper panel).
    Visual training will include observation of natural shape traces that were recorded during production by other participants in the visuo-motor training groups. Each pair of participants assigned to the visual group will be randomly yoked to one reference participant in the visuo-motor group. Participants will observe the visual output of their reference participant’s tracing overlaid on the corresponding template that was traced, in the same order as it was performed. One of these participants will be assigned to the dynamic visual input training group and observe videos of the reference participant’s produced traces evolve over time, and the other participant will be assigned to the static visual input training group and observe a static image of the full end-point trace, appearing at once and presented for the duration it took to be traced (Fig 3B lower panel).
    For all training regimens, shapes will be presented in the center of the screen and take up 14 degrees of visual angle. Each shape will be repeatedly traced or observed 25 times throughout each training session, for an overall of 200 trials per training session (8 shapes x 25 repetitions). Based on our pilot experiments, this takes approximately 50 minutes to complete in the first session, and duration decreases as participants become more skilled and increase their movement speed. Our pilot results (Fig. 3) indicate that this amount of training corresponds to concurrent improvement in visual perception. Further exploration is needed to ascertain the different training conditions that are most efficient in inducing this improvement.
    The complete experiment will include 3 sessions overall, within an 8-day period: 2 sessions on consecutive days for the training regimen, and another post-training assessment session (1 week after the first training session) to measure retention of visual shape discrimination. Each of the two training sessions will start and end with an assessment of visual discrimination between the trained shapes, before and after the training task. The third, post-training session will include only a visual assessment.
    Training task: Each participant will be randomly assigned to one of six training task groups which include two visuo-motor training regimen groups (right / left hand tracing), and four visual training regimen groups (dynamic / static visual input, from right/left hand traces).
    Visuo-motor training will include tracing of shapes and receiving visual feedback of the trace as it is formed. Participants assigned to one of the visuo-motor training regimens will be asked to use an electronic stylus to trace a template of a different shape in each trial. Shapes from the training set will be randomly ordered across training. Shapes will be traced continuously for one full cycle, in a comfortable natural pace. Participants will see the reference template throughout the trial, and their trace will form in real-time overlaid on the template, as if drawing with a pen on paper. Any starting position and direction of tracing can be freely chosen by the participant. Prior to the training session on the first day, each shape will also be traced one time in a pre-training run, so participants are comfortable with the set-up and familiar with the shapes before training begins. Tracing will be performed either using the non-dominant left hand or the dominant right hand, according to the assigned training group (Fig 3B upper panel).
    Visual training will include observation of natural shape traces that were recorded during production by other participants in the visuo-motor training groups. Each pair of participants assigned to the visual group will be randomly yoked to one reference participant in the visuo-motor group. Participants will observe the visual output of their reference participant’s tracing overlaid on the corresponding template that was traced, in the same order as it was performed. One of these participants will be assigned to the dynamic visual input training group and observe videos of the reference participant’s produced traces evolve over time, and the other participant will be assigned to the static visual input training group and observe a static image of the full end-point trace, appearing at once and presented for the duration it took to be traced (Fig 3B lower panel).
    For all training regimens, shapes will be presented in the center of the screen and take up 14 degrees of visual angle. Each shape will be repeatedly traced or observed 25 times throughout each training session, for an overall of 200 trials per training session (8 shapes x 25 repetitions). Based on our pilot experiments, this takes approximately 50 minutes to complete in the first session, and duration decreases as participants become more skilled and increase their movement speed. Our pilot results (Fig. 3) indicate that this amount of training corresponds to concurrent improvement in visual perception. Further exploration is needed to ascertain the different training conditions that are most efficient in inducing this improvement.
    The complete experiment will include 3 sessions overall, within an 8-day period: 2 sessions on consecutive days for the training regimen, and another post-training assessment session (1 week after the first training session) to measure retention of visual shape discrimination. Each of the two training sessions will start and end with an assessment of visual discrimination between the trained shapes, before and after the training task. The third, post-training session will include only a visual assessment.


* Visual assessment task:
        To assess our participants’ ability to discriminate between shapes, we will use a delayed match to sample design (Fig. 2A). Each trial will be initiated by the participant placing the stylus at a designated location at the bottom center of the screen (marked as the home location), to indicate their readiness. A trial will begin with the target shape presented for 1000ms, followed by a 300ms visual mask, and a screen with all the shapes in the sample set, presented on a semi-circle, equidistant from the home location. Participants will be instructed to indicate which among the sample set is the target shape (shown in the first screen), by reaching to the chosen shape as quickly as possible. Each shape will serve as target 8 times (yielding 8x8=64 trials per family), and presentation location of the samples will be counterbalanced across trials.

* Training task


* Imaging session
        During the fMRI session, participants will be engaged in viewing of the same template shapes as in the behavioral session, while their neural activity will be recorded. Each participant will observe two types of experimental conditions: a block design wherein each block will be comprised of all 8 different template shapes in a  pseudo-randomized order [actually two block types of 4 images each], and a block design wherein there will be three types of blocks - each type consisting of repeated presentations of a single shape (three distinct shapes overall).
        The three shapes displayed in the second condition will be chosen per participant, based on the confusion matrix of their responses in the final visual assessment, such that two of the shapes are the most-confused pair, and the third shape is the least-confused shape with regards to one of the shapes in the pair.

        Throughout the experiment, templates will be presented on an MR-compatible screen viewed from a head-mounted mirror, as commonly used in imaging experiments (see Fig. 4C). The experiment will consist of 6 runs and a preliminary localizer run (two for the first experimental condition and four for the second). Each run of the first condition will  contain a total of 20 blocks, and each run of the second condition will include a total of 24 blocks (8 blocks of each shape).

*** TODO a paragraph about the one-back task.

* Data acquisition and preprocessing:
        Same as study 2


* Analysis
*** Localizer analysis:
            Data from the localizer run will be analyzed using a general linear model approach. In the shapes localizer, we will use the contrast of (shape family 1 + shape family 2) > rest to detect visual areas sensitive to the presentation of our shapes (shape ROI).
*** TODO shouldn't I be using a more specific localizer too ?

*** MVPA
    Same as study   2

*** Analysis 1: classification of training regimen
        To examine how active production (tracing) of shapes affects their neural representation in visual cortex (question 1), we will use MVPA to discriminate between subjects who were trained in either regimen based on their brain activity during shape observation.

        As an additional analysis, we will compute a correlation matrix between the signal  in each voxel and the rest of the voxels in both ROIs (the signal as a time series, averaged across all blocks). Next we'll compute an intra-group similarity score in the following way: for every choice of two subjects, one from each group, we'll compute the similarity between their correlation matrices and those of both groups. The similarity score of a group will be defined as the number of times (i.e the number of pairs for which -) the correlation matrix of the subject from that group was closer to the group's correlation matrix than to that of the other group. (Is this clear enough? Too much detail?)

***** MVPA on ROIs
***** a cross-correlation matrix between all voxels in the ROIs
******* repeated leave one out
******* compute matching score


*** Analysis 2: correlation between classification of individual shapes and behavioral/kinematic measures
        To examine how active production (tracing) of shapes affects their neural representation in visual and motor cortex (question 2), we will use MVPA to classify the observed shape identity - discriminating between the most confused pair, and between the least confused pair as inferred from the visual assessment. We will then use the accuracy of the latter as a way to normalize the score of the former: the least confused pair should be the easiest to discriminate between, and thus is the upper limit of our algorithm's ability to discriminate these shapes in a given subject.
        Next, we will check for a correlation between the normalized classification accuracy and the visual assessment score, and between the normalized classification accuracy and the smoothness of the traces collected during the behavioral training sessions. Smoothness will be defined as the degree to which the acceleration changes along the course of the movement (minimum jerk? - cite a source). Higher classification accuracy will be interpreted as better separation in the neural representation of the two shapes, and higher smoothness scores as reflecting better motor planning, which in turn is taken to reflect higher degree of internalization of the shapes. We expect to find a positive correlation in both tests.
        A positive correlation with kinematic measures could be interpreted as supporting  idea that  shape representation is reliant on the same motor circuits which are recruited during shape generation/tracing. What will a lack of correlation say?

***** use MVPA to decode which of the three shapes was observed
***** normalize the most confused prediction score by the least confused score
***** check correlation between normalized score and assessment score
***** check correlation between normalized score and smoothness/accuracy
